geo $trusted_proxy {

    default 0;

    172.30.0.11 1;
    172.30.0.12 1;
    172.30.0.13 1;
}
#
# если XFF уже существует
#

map $http_x_forwarded_for $xff_prefix {

    "" "";

    default "$http_x_forwarded_for, ";
}

#
# формируем корректный XFF
#

map $trusted_proxy $real_xff {

    #
    # запрос пришел от клиента
    # -> уничтожаем поддельный XFF
    #

    0 $remote_addr;

    #
    # запрос пришел от доверенного nginx
    # -> продолжаем цепочку
    #

    1 "${xff_prefix}$remote_addr";
}
