geo $trusted_proxy {

    default 0;

    172.30.0.11 1;
    172.30.0.12 1;
    172.30.0.13 1;
}


map $http_x_forwarded_for $xff_prefix {

    "" "";

    default "$http_x_forwarded_for, ";
}



map $trusted_proxy $real_xff {



    0 $remote_addr;



    1 "${xff_prefix}$remote_addr";
}
